# ==============================================================================
#  🛡️ SISTEMA DIGITAL DE PROTECCIÓN CIVIL Y BOMBEROS
#  Copyright (c) 2026 Josué Jaziel Delgado Burela. Todos los derechos reservados.
#  Desarrollado y Diseñado por: Josué Jaziel Delgado Burela
#  Contacto y Soporte: jburela1@gmal.com
# ==============================================================================

# Generated by Django 6.0.6 on 2026-07-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField(blank=True, help_text='Lista de requisitos separados por comas')),
                ('area', models.CharField(choices=[('PC', 'Protección Civil'), ('IU', 'Imagen Urbana'), ('LOG', 'Logística y Operaciones')], default='PC', max_length=3)),
                ('icono', models.CharField(choices=[('documento', 'Documento / Licencia'), ('riesgo', 'Cámara / Reporte de Riesgo'), ('maletin', 'Maletín / Comercial'), ('operacion', 'Engranaje / Operaciones')], default='documento', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
