# ==============================================================================
#  🛡️ SISTEMA DIGITAL DE PROTECCIÓN CIVIL Y BOMBEROS
#  Copyright (c) 2026 Josué Jaziel Delgado Burela. Todos los derechos reservados.
#  Desarrollado y Diseñado por: Josué Jaziel Delgado Burela
#  Contacto y Soporte: jburela1@gmal.com
# ==============================================================================

# Generated by Django 6.0.6 on 2026-07-06 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_tramite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='icono',
            field=models.CharField(choices=[('documento', 'Documento / Trámite'), ('riesgo', 'Cámara / Reporte de Riesgo'), ('maletin', 'Maletín / Comercial'), ('operacion', 'Engranaje / Operaciones')], default='documento', max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitudTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=13)),
                ('pdf_documento', models.FileField(upload_to='expedientes/')),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Por Validar'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='portal.tramite')),
            ],
        ),
    ]
