# ==============================================================================
#  🛡️ SISTEMA DIGITAL DE PROTECCIÓN CIVIL Y BOMBEROS
#  Copyright (c) 2026 Josué Jaziel Delgado Burela. Todos los derechos reservados.
#  Desarrollado y Diseñado por: Josué Jaziel Delgado Burela
#  Contacto y Soporte: jburela1@gmal.com
# ==============================================================================

# Generated by Django 6.0.6 on 2026-07-06 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_tramite_icono_solicitudtramite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reporte', models.CharField(editable=False, max_length=15, unique=True)),
                ('nombre_ciudadano', models.CharField(max_length=150)),
                ('telefono_ciudadano', models.CharField(max_length=10)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('tipo_servicio', models.CharField(choices=[('GAS', 'Fuga de Gas / Material Peligroso'), ('FUEGO', 'Incendio / Conato de Fuego'), ('ARBOL', 'Árbol Caído / Obstrucción de Vía'), ('AGUA', 'Inundación / Encharcamiento Crítico'), ('CABLE', 'Cables Expuestos / Postes Caídos'), ('ABEJAS', 'Enjambre de Abejas'), ('CHOQUE', 'Accidente Vial / Choque'), ('OTRO', 'Otro Incidente de Riesgo')], default='OTRO', max_length=10)),
                ('direccion', models.CharField(max_length=255)),
                ('colonia', models.CharField(max_length=100)),
                ('localidad', models.CharField(default='Medellín de Bravo', max_length=100)),
                ('descripcion', models.TextField()),
                ('evidencia_foto', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta / Emergencia')], default='MEDIA', max_length=10)),
                ('unidad_acudira', models.CharField(blank=True, max_length=100, null=True)),
                ('dependencia_conocimiento', models.CharField(blank=True, max_length=200, null=True)),
                ('tiempo_atencion', models.CharField(blank=True, max_length=50, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente / Sin Atender'), ('EN_PROCESO', 'En Curso / Equipo en Camino'), ('RESUELTO', 'Resuelto / Atendido')], default='PENDIENTE', max_length=15)),
                ('responsables', models.ManyToManyField(blank=True, related_name='reportes_atendidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
