# ==============================================================================
#  🛡️ SISTEMA DIGITAL DE PROTECCIÓN CIVIL Y BOMBEROS
#  Copyright (c) 2026 Josué Jaziel Delgado Burela. Todos los derechos reservados.
#  Desarrollado y Diseñado por: Josué Jaziel Delgado Burela
#  Contacto y Soporte: jburela1@gmal.com
# ==============================================================================

# Generated by Django 6.0.6 on 2026-07-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_ciudadano'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
