# ==============================================================================
#  🛡️ SISTEMA DIGITAL DE PROTECCIÓN CIVIL Y BOMBEROS
#  Copyright (c) 2026 Josué Jaziel Delgado Burela. Todos los derechos reservados.
#  Desarrollado y Diseñado por: Josué Jaziel Delgado Burela
#  Contacto y Soporte: jburela1@gmal.com
# ==============================================================================

# Generated by Django 6.0.6 on 2026-07-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_historialreporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtramite',
            name='capacidad_fija',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='correo_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='doc_croquis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='doc_fotos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='doc_ine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='doc_predial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='domicilio_calle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='entre_calles',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='giro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='horario_funcionamiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='no_ext',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='no_int',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='propietario_representante',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_capacitacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_corresponsabilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_electrico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_estructural',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_gas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_programa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_seguro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='superficie_m2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='tipo_anuencia',
            field=models.CharField(blank=True, choices=[('OPERATIVA', 'Anuencia de operativa de protección civil a instalaciones públicas y privadas'), ('RENOVACION', 'Renovación de anuencia operativa'), ('RECOMENDACIONES', 'Pliego de Recomendaciones de eventos masivos'), ('TEMPORAL', 'Temporal (verificación de seguridad para puestos ambulantes)')], default='OPERATIVA', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='unidad_interna_nombre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='unidad_interna_tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='form_type',
            field=models.CharField(choices=[('GENERAL', 'Carga de Expediente PDF General'), ('ANUENCIA_PC', 'Solicitud de Anuencia Protección Civil (Formato 1 de 5)')], default='GENERAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudtramite',
            name='pdf_documento',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/'),
        ),
    ]
