# ==============================================================================
#  🛡️ SISTEMA DIGITAL DE PROTECCIÓN CIVIL Y BOMBEROS
#  Copyright (c) 2026 Josué Jaziel Delgado Burela. Todos los derechos reservados.
#  Desarrollado y Diseñado por: Josué Jaziel Delgado Burela
#  Contacto y Soporte: jburela1@gmal.com
# ==============================================================================

# Generated by Django 6.0.6 on 2026-07-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_solicitudtramite_capacidad_fija_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtramite',
            name='inspeccion_atiende',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_analisis_riesgo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_anuencia_vecinos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_bitacora_anuncio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_responsiva_estabilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='tipo_anuencia_anuncio',
            field=models.CharField(blank=True, choices=[('ANUNCIO', 'Anuencia de anuncio de Protección Civil'), ('ANTENA', 'Anuencia de antena de Protección Civil'), ('RENOVACION_ANUNCIO', 'Renovación de anuencia de anuncio de Protección Civil')], default='ANUNCIO', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='form_type',
            field=models.CharField(choices=[('GENERAL', 'Carga de Expediente PDF General'), ('ANUENCIA_PC', 'Solicitud de Anuencia Protección Civil (Formato 1 de 5)'), ('ANUNCIOS_PC', 'Solicitud de Anuencia de Anuncios y Antenas (Formato 2 de 5)')], default='GENERAL', max_length=30),
        ),
    ]
