# ==============================================================================
#  🛡️ SISTEMA DIGITAL DE PROTECCIÓN CIVIL Y BOMBEROS
#  Copyright (c) 2026 Josué Jaziel Delgado Burela. Todos los derechos reservados.
#  Desarrollado y Diseñado por: Josué Jaziel Delgado Burela
#  Contacto y Soporte: jburela1@gmal.com
# ==============================================================================

# Generated by Django 6.0.6 on 2026-07-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_solicitudtramite_inspeccion_atiende_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_analisis_riesgo',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_anuencia_vecinos',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_bitacora_anuncio',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_capacitacion',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_corresponsabilidad',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_croquis',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_electrico',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_estructural',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_fotos',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_gas',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_ine',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_pago',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_predial',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_programa',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_responsiva_estabilidad',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_seguro',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
    ]
