# ==============================================================================
#  🛡️ SISTEMA DIGITAL DE PROTECCIÓN CIVIL Y BOMBEROS
#  Copyright (c) 2026 Josué Jaziel Delgado Burela. Todos los derechos reservados.
#  Desarrollado y Diseñado por: Josué Jaziel Delgado Burela
#  Contacto y Soporte: jburela1@gmal.com
# ==============================================================================

# Generated by Django 6.0.6 on 2026-07-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_reporteriesgo_ciudadano_solicitudtramite_ciudadano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteriesgo',
            name='costo_material',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporteriesgo',
            name='costo_personal',
            field=models.IntegerField(default=0),
        ),
    ]
