# ==============================================================================
#  🛡️ SISTEMA DIGITAL DE PROTECCIÓN CIVIL Y BOMBEROS
#  Copyright (c) 2026 Josué Jaziel Delgado Burela. Todos los derechos reservados.
#  Desarrollado y Diseñado por: Josué Jaziel Delgado Burela
#  Contacto y Soporte: jburela1@gmal.com
# ==============================================================================

# Generated by Django 6.0.6 on 2026-07-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_reporteriesgo_fecha_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteriesgo',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente / Sin Atender'), ('LEIDO', 'Leído / Evaluando'), ('EN_PROCESO', 'En Camino / Atendiendo'), ('RESUELTO', 'Finalizado / Resuelto')], default='PENDIENTE', max_length=15),
        ),
    ]
