# ==============================================================================
#  🛡️ SISTEMA DIGITAL DE PROTECCIÓN CIVIL Y BOMBEROS
#  Copyright (c) 2026 Josué Jaziel Delgado Burela. Todos los derechos reservados.
#  Desarrollado y Diseñado por: Josué Jaziel Delgado Burela
#  Contacto y Soporte: jburela1@gmal.com
# ==============================================================================

# Generated by Django 6.0.6 on 2026-07-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_alter_reporteriesgo_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='sub_tipo',
            field=models.CharField(blank=True, help_text='Subcategoría de trámite (ej. OPERATIVA, RENOVACION, ANUNCIO, etc.)', max_length=30, null=True),
        ),
    ]
