# ==============================================================================
#  🛡️ SISTEMA DIGITAL DE PROTECCIÓN CIVIL Y BOMBEROS
#  Copyright (c) 2026 Josué Jaziel Delgado Burela. Todos los derechos reservados.
#  Desarrollado y Diseñado por: Josué Jaziel Delgado Burela
#  Contacto y Soporte: jburela1@gmal.com
# ==============================================================================

# Generated by Django 6.0.6 on 2026-07-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_tramite_sub_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtramite',
            name='doc_titulo_propiedad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_constancia_no_afectacion',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_plano_arquitectonico',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_titulo_propiedad',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_uso_suelo',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='realiza_correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='realiza_nombre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='realiza_telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_constancia_no_afectacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_plano_arquitectonico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_uso_suelo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='superficie_construccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='superficie_terreno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='tipo_anuencia_construccion',
            field=models.CharField(blank=True, choices=[('CONSTRUCCION', 'Revisión de planos, proyecto para No inconveniente de construcción'), ('REMODELACION', 'Inspección de inmueble y revisión de planos para remodelación y ampliación'), ('DEMOLICION', 'Inspección de inmueble a demoler')], default='CONSTRUCCION', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='form_type',
            field=models.CharField(choices=[('GENERAL', 'Carga de Expediente PDF General'), ('ANUENCIA_PC', 'Solicitud de Anuencia Protección Civil (Formato 1 de 5)'), ('ANUNCIOS_PC', 'Solicitud de Anuencia de Anuncios y Antenas (Formato 2 de 5)'), ('CONSTRUCCION_PC', 'Solicitud de Anuencia para Construcción, Remodelación y Demolición (Formato 3 de 5)')], default='GENERAL', max_length=30),
        ),
    ]
