# ==============================================================================
#  🛡️ SISTEMA DIGITAL DE PROTECCIÓN CIVIL Y BOMBEROS
#  Copyright (c) 2026 Josué Jaziel Delgado Burela. Todos los derechos reservados.
#  Desarrollado y Diseñado por: Josué Jaziel Delgado Burela
#  Contacto y Soporte: jburela1@gmal.com
# ==============================================================================

# Generated by Django 6.0.6 on 2026-07-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_solicitudtramite_doc_titulo_propiedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_cedula_estatal',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='file_curriculum',
            field=models.FileField(blank=True, null=True, upload_to='requisitos/'),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_cedula_estatal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='req_curriculum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudtramite',
            name='tipo_anuencia_terceros',
            field=models.CharField(blank=True, choices=[('NUEVO_INGRESO', 'Registro de Tercer Acreditado y/o Empresas Capacitadoras e Instructores (Nuevo Ingreso)'), ('RENOVACION_REGISTRO', 'Renovación de Registro en el Padrón Municipal')], default='NUEVO_INGRESO', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='form_type',
            field=models.CharField(choices=[('GENERAL', 'Carga de Expediente PDF General'), ('ANUENCIA_PC', 'Solicitud de Anuencia Protección Civil (Formato 1 de 5)'), ('ANUNCIOS_PC', 'Solicitud de Anuencia de Anuncios y Antenas (Formato 2 de 5)'), ('CONSTRUCCION_PC', 'Solicitud de Anuencia para Construcción, Remodelación y Demolición (Formato 3 de 5)'), ('TERCEROS_PC', 'Registro de Terceros Acreditados y Capacitadores (Formato 4 de 5)')], default='GENERAL', max_length=30),
        ),
    ]
