# ==============================================================================
#  🛡️ SISTEMA DIGITAL DE PROTECCIÓN CIVIL Y BOMBEROS
#  Copyright (c) 2026 Josué Jaziel Delgado Burela. Todos los derechos reservados.
#  Desarrollado y Diseñado por: Josué Jaziel Delgado Burela
#  Contacto y Soporte: jburela1@gmal.com
# ==============================================================================

# Generated by Django 6.0.6 on 2026-07-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_localidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadGiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('actividad', models.CharField(max_length=255)),
                ('riesgo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Actividad y Giro de Riesgo',
                'verbose_name_plural': 'Actividades y Giros de Riesgo',
                'ordering': ['numero'],
            },
        ),
    ]
