# Generated by Django 6.0.6 on 2026-07-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_actividadgiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(help_text='Formato WhatsApp (ej. 5212291234567)', max_length=20)),
                ('categoria', models.CharField(choices=[('BOMBERO', 'Bomberos'), ('AMBULANCIA', 'Ambulancias / Paramédicos'), ('POLICIA', 'Policía Municipal')], max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trabajador de Emergencia',
                'verbose_name_plural': 'Trabajadores de Emergencia',
                'ordering': ['nombre'],
            },
        ),
    ]
