# Generated by Django 6.0.6 on 2026-07-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='turno',
            field=models.CharField(choices=[('TURNO_1', 'Turno 1 (00:00 - 12:00)'), ('TURNO_2', 'Turno 2 (12:00 - 00:00)')], default='TURNO_1', max_length=10),
        ),
    ]
