# Generated by Django 6.0.6 on 2026-07-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_trabajador_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='codigo_2fa',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='codigo_2fa_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='estado_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
