# Generated by Django 6.0.6 on 2026-07-23 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_ciudadano_codigo_2fa_ciudadano_codigo_2fa_expiracion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAnuenciaPC',
            fields=[
                ('solicitudtramite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.solicitudtramite')),
            ],
            options={
                'verbose_name': 'Solicitud de Anuencia PC (Formato 1)',
                'verbose_name_plural': 'Solicitudes de Anuencia PC',
            },
            bases=('portal.solicitudtramite',),
        ),
        migrations.CreateModel(
            name='SolicitudAnunciosPC',
            fields=[
                ('solicitudtramite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.solicitudtramite')),
            ],
            options={
                'verbose_name': 'Solicitud de Anuncio/Antena (Formato 2)',
                'verbose_name_plural': 'Solicitudes de Anuncios y Antenas',
            },
            bases=('portal.solicitudtramite',),
        ),
        migrations.CreateModel(
            name='SolicitudConstruccionPC',
            fields=[
                ('solicitudtramite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.solicitudtramite')),
            ],
            options={
                'verbose_name': 'Solicitud de Construcción (Formato 3)',
                'verbose_name_plural': 'Solicitudes de Construcción',
            },
            bases=('portal.solicitudtramite',),
        ),
        migrations.CreateModel(
            name='SolicitudTercerosPC',
            fields=[
                ('solicitudtramite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.solicitudtramite')),
            ],
            options={
                'verbose_name': 'Solicitud de Tercero Acreditado (Formato 4)',
                'verbose_name_plural': 'Solicitudes de Terceros Acreditados',
            },
            bases=('portal.solicitudtramite',),
        ),
        migrations.AlterModelOptions(
            name='reporteriesgo',
            options={'verbose_name': 'Reporte de Riesgo', 'verbose_name_plural': 'Reportes de Riesgos'},
        ),
        migrations.AlterModelOptions(
            name='solicitudtramite',
            options={'verbose_name': 'Solicitud de Trámite', 'verbose_name_plural': 'Solicitudes de Trámites'},
        ),
        migrations.AddIndex(
            model_name='reporteriesgo',
            index=models.Index(fields=['estatus', '-fecha_reporte'], name='idx_reporte_estatus_fecha'),
        ),
        migrations.AddIndex(
            model_name='reporteriesgo',
            index=models.Index(fields=['tipo_servicio', 'estatus'], name='idx_reporte_servicio_estatus'),
        ),
        migrations.AddIndex(
            model_name='reporteriesgo',
            index=models.Index(fields=['prioridad', 'estatus'], name='idx_reporte_prioridad_estatus'),
        ),
        migrations.AddIndex(
            model_name='reporteriesgo',
            index=models.Index(fields=['numero_reporte'], name='idx_reporte_folio'),
        ),
        migrations.AddIndex(
            model_name='solicitudtramite',
            index=models.Index(fields=['estatus', '-creado_en'], name='idx_solicitud_estatus_fecha'),
        ),
        migrations.AddIndex(
            model_name='solicitudtramite',
            index=models.Index(fields=['tramite', 'estatus'], name='idx_solicitud_tramite_estatus'),
        ),
        migrations.AddIndex(
            model_name='solicitudtramite',
            index=models.Index(fields=['ciudadano', '-creado_en'], name='idx_solicitud_ciudadano_fecha'),
        ),
        migrations.AddIndex(
            model_name='solicitudtramite',
            index=models.Index(fields=['rfc'], name='idx_solicitud_rfc'),
        ),
    ]
