# Generated by Django 6.0.6 on 2026-07-27 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_solicitudanuenciapc_solicitudanunciospc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('jornada_tipo', models.CharField(choices=[('24H', 'Jornada de 24 Horas'), ('12H_M', 'Jornada 12 Horas (Día)'), ('12H_N', 'Jornada 12 Horas (Noche)'), ('ESPECIAL', 'Operativo Especial / Relevo')], default='24H', max_length=15)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#5A123E', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('trabajadores', models.ManyToManyField(blank=True, related_name='plantillas', to='portal.trabajador')),
            ],
            options={
                'verbose_name': 'Plantilla de Guardia',
                'verbose_name_plural': 'Plantillas de Guardias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='portal.plantillaguardia')),
            ],
            options={
                'verbose_name': 'Programación de Guardia',
                'verbose_name_plural': 'Programaciones de Guardias',
                'ordering': ['fecha'],
            },
        ),
    ]
