# Generated by Django 6.0.6 on 2026-07-27 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_plantillaguardia_programacionguardia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='excel_uploads/')),
                ('resumen_json', models.JSONField(blank=True, null=True)),
                ('filas_totales', models.IntegerField(default=0)),
                ('columnas_totales', models.IntegerField(default=0)),
                ('hojas_nombres', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dataset de Excel Analizado',
                'verbose_name_plural': 'Datasets de Excel Analizados',
                'ordering': ['-creado_en'],
            },
        ),
    ]
