# Generated by Django 6.0.6 on 2026-08-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_datasetexcel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatasetExcel',
        ),
    ]
