# Generated by Django 6.0.6 on 2026-08-02 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_delete_datasetexcel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteriesgo',
            name='costo_material',
        ),
        migrations.RemoveField(
            model_name='reporteriesgo',
            name='costo_personal',
        ),
    ]
