# Generated by Django 6.0.6 on 2026-08-02 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_remove_reporteriesgo_costo_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionAtencionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('paso', models.IntegerField(default=1)),
                ('unidad_acudira', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.reporteriesgo')),
            ],
            options={
                'verbose_name': 'Sesión de Atención WhatsApp',
                'verbose_name_plural': 'Sesiones de Atención WhatsApp',
            },
        ),
    ]
