# Generated by Django 6.0.6 on 2026-08-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_sesionatencionwhatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='numero_empleado',
            field=models.CharField(blank=True, help_text='Folio asignado automáticamente ej. BOM-0001', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Contraseña encriptada para acceso a la App Móvil', max_length=128),
        ),
    ]
