# Generated by Django 6.0.6 on 2026-08-15 00:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_trabajador_is_active_trabajador_numero_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolGuardiaFirmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_periodo', models.DateField(default=django.utils.timezone.now)),
                ('guardia_tipo', models.CharField(choices=[('GUARDIA_1', 'Guardia 1'), ('GUARDIA_2', 'Guardia 2'), ('GUARDIA_3', 'Guardia 3'), ('GENERAL', 'Rol Completo (Guardias 1 y 2)')], default='GENERAL', max_length=20)),
                ('comandante_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones_novedades', models.TextField(blank=True, null=True)),
                ('imagen_documento_firmado', models.FileField(upload_to='roles_guardia/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de Guardia Firmado',
                'verbose_name_plural': 'Roles de Guardias Firmados',
                'ordering': ['-fecha_periodo', '-creado_en'],
            },
        ),
    ]
