# Generated by Django 6.0.6 on 2026-08-18 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_rolguardiafirmado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'Configuración de Inspección',
                'verbose_name_plural': 'Configuraciones de Inspección',
            },
        ),
        migrations.CreateModel(
            name='ContactoDirectorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('puesto', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('web', models.CharField(blank=True, max_length=150, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='directorio/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contacto de Directorio',
                'verbose_name_plural': 'Contactos de Directorio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corta', models.DateField()),
                ('fecha_texto', models.CharField(max_length=150)),
                ('horario', models.CharField(default='De 10am A 2pm', max_length=100)),
                ('rutas_resumen', models.CharField(max_length=255)),
                ('inspector', models.CharField(max_length=150)),
                ('operador', models.CharField(max_length=150)),
                ('director', models.CharField(default='L.E.D. DANIEL EDUARDO ROMERO PILAR', max_length=150)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado')], default='Pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Orden de Inspección',
                'verbose_name_plural': 'Órdenes de Inspecciones',
                'ordering': ['-fecha_corta', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('ruta', models.CharField(max_length=150)),
                ('establecimiento', models.CharField(max_length=255)),
                ('mes_pago', models.CharField(blank=True, default='', max_length=50)),
                ('realizado', models.CharField(blank=True, default='', max_length=50)),
                ('pendiente', models.CharField(blank=True, default='', max_length=50)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.ordeninspeccion')),
            ],
            options={
                'verbose_name': 'Ítem de Inspección',
                'verbose_name_plural': 'Ítems de Inspección',
                'ordering': ['numero'],
            },
        ),
    ]
