# Generated by Django 6.0.6 on 2026-08-18 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_configuracioninspeccion_contactodirectorio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolGuardiaConfigurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('guardia_tipo', models.CharField(choices=[('GUARDIA_1', 'Guardia 1'), ('GUARDIA_2', 'Guardia 2'), ('GENERAL', 'Rol Completo (Guardias 1 y 2)')], default='GENERAL', max_length=20)),
                ('comandante_g1', models.CharField(blank=True, default='Comandante / Jefe de Guardia', max_length=150, null=True)),
                ('comandante_g2', models.CharField(blank=True, default='Comandante / Jefe de Guardia', max_length=150, null=True)),
                ('datos_json', models.TextField(default='{}')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de Guardia Configurado',
                'verbose_name_plural': 'Roles de Guardias Configurados',
                'ordering': ['-fecha'],
            },
        ),
    ]
