# Generated by Django 6.0.6 on 2026-08-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_rolguardiaconfigurado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaInformativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_oficio', models.CharField(max_length=150)),
                ('asunto', models.CharField(max_length=255)),
                ('lugar_fecha', models.CharField(max_length=200)),
                ('destinatario_nombre', models.CharField(max_length=200)),
                ('destinatario_cargo', models.CharField(max_length=200)),
                ('destinatario_dependencia', models.CharField(blank=True, max_length=200, null=True)),
                ('atencion_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('atencion_cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('cuerpo_texto', models.TextField()),
                ('firmante_nombre', models.CharField(default='LIC. DANIEL EDUARDO ROMERO PILAR', max_length=200)),
                ('firmante_cargo', models.TextField(default='TITULAR DE LA UNIDAD MUNICIPAL DE PROTECCIÓN CIVIL Y BOMBEROS DEL H. AYUNTAMIENTO MEDELLÍN DE BRAVO, VER.')),
                ('ccp_lineas', models.TextField(default='C.c. p -. Presidencia\nC.c.p -. Archivo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ficha Informativa / Oficio',
                'verbose_name_plural': 'Fichas Informativas y Oficios',
                'ordering': ['-creado_en'],
            },
        ),
    ]
