# Generated by Django 6.0.6 on 2026-08-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_fichainformativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichainformativa',
            name='hora_arribo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fichainformativa',
            name='hora_reporte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fichainformativa',
            name='lugar_hechos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichainformativa',
            name='tipo_documento',
            field=models.CharField(choices=[('OFICIO', 'Oficio Municipal / Solicitud'), ('TARJETA_INFORMATIVA', 'Tarjeta Informativa de Emergencias / Hechos')], default='OFICIO', max_length=30),
        ),
        migrations.AlterField(
            model_name='fichainformativa',
            name='ccp_lineas',
            field=models.TextField(blank=True, default='C.c. p -. Presidencia\nC.c.p -. Archivo', null=True),
        ),
        migrations.AlterField(
            model_name='fichainformativa',
            name='destinatario_cargo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fichainformativa',
            name='destinatario_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fichainformativa',
            name='num_oficio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
