# Generated by Django 6.0.6 on 2026-08-20 21:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_fichainformativa_hora_arribo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unidad', models.CharField(help_text='Ej. 208, 072, 096', max_length=50, unique=True)),
                ('nombre_identificador', models.CharField(help_text='Ej. Ambulancia 208, Pipa 072', max_length=150)),
                ('tipo_vehiculo', models.CharField(choices=[('Ambulancia', 'Ambulancia'), ('Pipa', 'Pipa de Agua'), ('PickUp', 'Pick Up / Camioneta Operativa'), ('Rescate', 'Unidad de Rescate'), ('Moto', 'Motocicleta Operativa'), ('Bomberos', 'Camión de Bomberos')], default='Ambulancia', max_length=50)),
                ('placas', models.CharField(blank=True, help_text='Placas de la unidad', max_length=50, null=True)),
                ('foto_unidad', models.ImageField(blank=True, null=True, upload_to='vehiculos/fotos/')),
                ('estatus', models.CharField(choices=[('DISPONIBLE', '🟢 Disponible'), ('EN_SERVICIO', '🔴 En Servicio (No Disponible)'), ('MANTENIMIENTO', '🛠️ En Mantenimiento'), ('FUERA_DE_SERVICIO', '⚠️ Fuera de Servicio')], default='DISPONIBLE', max_length=30)),
                ('odometro_actual', models.PositiveIntegerField(default=0, help_text='Kilometraje actual del odómetro')),
                ('nivel_gasolina_actual', models.CharField(choices=[('Reserva', '⚠️ Reserva (Bajo)'), ('1/4', '1/4 de Tanque'), ('1/2', '1/2 de Tanque'), ('3/4', '3/4 de Tanque'), ('Lleno', '⛽ Tanque Lleno')], default='Lleno', max_length=30)),
                ('ultima_salida_finalizada', models.DateTimeField(blank=True, help_text='Fecha y hora del último retorno a base', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehículo de Flotilla',
                'verbose_name_plural': 'Vehículos de Flotilla',
                'ordering': ['numero_unidad'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCargaGasolina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.CharField(help_text='Nombre de quien realizó la carga', max_length=200)),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('litros_cargados', models.DecimalField(decimal_places=2, help_text='Litros surtidos', max_digits=8)),
                ('costo_total', models.DecimalField(decimal_places=2, help_text='Importe total en $ MXN', max_digits=10)),
                ('odometro_al_cargar', models.PositiveIntegerField(help_text='Kilometraje al momento de cargar')),
                ('foto_ticket_o_bomba', models.ImageField(blank=True, null=True, upload_to='vehiculos/tickets_gasolina/')),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_gasolina', to='portal.vehiculounidad')),
            ],
            options={
                'verbose_name': 'Carga de Gasolina',
                'verbose_name_plural': 'Cargas de Gasolina',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraSalidaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador_nombre', models.CharField(help_text='Nombre del operador o paramédico a cargo', max_length=200)),
                ('guardia_turno', models.CharField(blank=True, help_text='Ej. Paco / Guardia 1', max_length=100, null=True)),
                ('descripcion_servicio', models.TextField(help_text='Motivo / Descripción del servicio o llamada de emergencia')),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('odometro_salida', models.PositiveIntegerField(help_text='Kilometraje al salir')),
                ('gasolina_salida', models.CharField(choices=[('Reserva', '⚠️ Reserva (Bajo)'), ('1/4', '1/4 de Tanque'), ('1/2', '1/2 de Tanque'), ('3/4', '3/4 de Tanque'), ('Lleno', '⛽ Tanque Lleno')], default='Lleno', max_length=30)),
                ('foto_odometro_salida', models.ImageField(blank=True, null=True, upload_to='vehiculos/odometros_salida/')),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('odometro_llegada', models.PositiveIntegerField(blank=True, null=True)),
                ('gasolina_llegada', models.CharField(blank=True, choices=[('Reserva', '⚠️ Reserva (Bajo)'), ('1/4', '1/4 de Tanque'), ('1/2', '1/2 de Tanque'), ('3/4', '3/4 de Tanque'), ('Lleno', '⛽ Tanque Lleno')], max_length=30, null=True)),
                ('foto_odometro_llegada', models.ImageField(blank=True, null=True, upload_to='vehiculos/odometros_llegada/')),
                ('km_recorridos', models.PositiveIntegerField(default=0, help_text='Calculado: Odómetro Llegada - Odómetro Salida')),
                ('duracion_minutos', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='portal.vehiculounidad')),
            ],
            options={
                'verbose_name': 'Registro de Bitácora de Salida',
                'verbose_name_plural': 'Registros de Bitácora de Salidas',
                'ordering': ['-fecha_salida'],
            },
        ),
    ]
