# Generated by Django 6.0.6 on 2026-08-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_vehiculounidad_registrocargagasolina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioOperadorVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo (se guarda en MAYÚSCULAS)', max_length=200, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('rol', models.CharField(choices=[('OPERADOR', 'Operador / Paramédico'), ('ADMIN', 'Administrador de Flotilla')], default='OPERADOR', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', '🕒 Pendiente de Aprobación'), ('APROBADO', '🟢 Activo / Aprobado'), ('DESACTIVADO', '🔴 Desactivado / Suspendido'), ('RECHAZADO', '❌ Rechazado')], default='PENDIENTE', max_length=20)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operador de Vehículo',
                'verbose_name_plural': 'Operadores de Vehículos',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
