# Generated by Django 6.0.6 on 2026-08-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_usuariooperadorvehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacorasalidavehiculo',
            name='detalle_incongruencia_salida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bitacorasalidavehiculo',
            name='foto_gasolina_llegada',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/gasolina_llegada/'),
        ),
        migrations.AddField(
            model_name='bitacorasalidavehiculo',
            name='foto_gasolina_salida',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/gasolina_salida/'),
        ),
        migrations.AddField(
            model_name='bitacorasalidavehiculo',
            name='incongruencia_salida',
            field=models.BooleanField(default=False),
        ),
    ]
