# Generated by Django 6.0.6 on 2026-08-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_bitacorasalidavehiculo_detalle_incongruencia_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteriesgo',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS Latitud', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reporteriesgo',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Coordenada GPS Longitud', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiculounidad',
            name='latitud_base',
            field=models.DecimalField(decimal_places=7, default=19.0558, help_text='Coordenada GPS Latitud de Base', max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiculounidad',
            name='longitud_base',
            field=models.DecimalField(decimal_places=7, default=-96.1558, help_text='Coordenada GPS Longitud de Base', max_digits=10),
        ),
    ]
