# Generated by Django on 2026-08-21

from django.db import migrations

def limpiar_duplicados_localidades(apps, schema_editor):
    Localidad = apps.get_model('portal', 'Localidad')
    
    # 1. Eliminar duplicados o entradas ambiguas de San Ramon / Arboledas
    nombres_eliminar = [
        'San Ramón',
        'Finca San Ramón',
        'Finca San Ramón (San Martín)',
        'Dos Bocas [Termoeléctrica]',
        'Ejido el Tejar',
        'Desviación los Robles',
        'Playa de Vacas (Ejido)',
    ]
    
    for nombre in nombres_eliminar:
        Localidad.objects.filter(nombre=nombre).delete()

    # 2. Desduplicar cualquier otro nombre idéntico si existiera
    todos_nombres = Localidad.objects.values_list('nombre', flat=True)
    vistos = set()
    for nombre in list(todos_nombres):
        nombre_clean = nombre.strip()
        if nombre_clean.lower() in vistos:
            # Eliminar todos menos el primero
            objs = list(Localidad.objects.filter(nombre=nombre).order_by('id'))
            for duplicate in objs[1:]:
                duplicate.delete()
        else:
            vistos.add(nombre_clean.lower())

def reverse_code(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_reporteriesgo_latitud_reporteriesgo_longitud_and_more'),
    ]

    operations = [
        migrations.RunPython(limpiar_duplicados_localidades, reverse_code),
    ]
