# Generated by Django 6.0.6 on 2026-08-25 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_limpiar_localidades_duplicadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Curso / Capacitación')),
                ('descripcion', models.TextField(verbose_name='Descripción y Temario del Curso')),
                ('duracion_horas', models.PositiveIntegerField(default=8, verbose_name='Duración en Horas')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio / Impartición')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización (Opcional)')),
                ('horario', models.CharField(default='09:00 a 14:00 hrs', max_length=100, verbose_name='Horario')),
                ('sede_ubicacion', models.CharField(default='Estación Central de Bomberos El Tejar', max_length=200, verbose_name='Sede / Ubicación')),
                ('cupo_maximo', models.PositiveIntegerField(default=50, verbose_name='Cupo Máximo de Participantes')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Curso Activo para Registro Público?')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso de Capacitación',
                'verbose_name_plural': 'Cursos de Capacitación',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo (tal como aparecerá en Constancia)')),
                ('curp', models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP (Opcional)')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono / WhatsApp')),
                ('empresa_institucion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa / Institución Solicitante')),
                ('asistio', models.BooleanField(default=False, verbose_name='¿Asistió al Curso?')),
                ('aprobado', models.BooleanField(default=False, verbose_name='¿Aprobó y Cumplió Requisitos?')),
                ('folio_constancia', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Folio Único de Constancia')),
                ('codigo_qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_emision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Emisión de Constancia')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='portal.cursocapacitacion')),
            ],
            options={
                'verbose_name': 'Inscripción a Capacitación',
                'verbose_name_plural': 'Inscripciones a Capacitaciones',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
