# Generated by Django 6.0.6 on 2026-09-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_cursocapacitacion_inscripcioncapacitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcioncapacitacion',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico (Opcional)'),
        ),
        migrations.AlterField(
            model_name='inscripcioncapacitacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono / WhatsApp (Opcional)'),
        ),
    ]
