# Generated by Django 6.0.6 on 2026-09-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_cursocapacitacion_finalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursocapacitacion',
            name='finalizado',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='rol_vehicular',
            field=models.CharField(choices=[('NINGUNO', 'Sin acceso a vehículos'), ('OPERADOR', 'Operador / Paramédico / Bombero'), ('JEFE_GUARDIA', 'Jefe de Guardia (Supervisor)'), ('ADMIN', 'Administrador de Flotilla')], default='NINGUNO', max_length=20),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='ultimo_acceso_vehicular',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcioncapacitacion',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='inscripcioncapacitacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono / WhatsApp'),
        ),
    ]
