# Generated by Django 6.0.6 on 2026-09-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_remove_cursocapacitacion_finalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursocapacitacion',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='¿Curso Finalizado / Pasado?'),
        ),
    ]
