# Generated by Django 6.0.6 on 2026-09-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_cursocapacitacion_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacorasalidavehiculo',
            name='operador_telefono',
            field=models.CharField(blank=True, help_text='Número de WhatsApp del operador', max_length=50, null=True),
        ),
    ]
